SHELL := /bin/bash

.PHONY: help format lint test build imsg clean build-dylib start install uninstall dock-app

INSTALL_DIR ?= $(HOME)/.local/bin
WRAPPER     := $(INSTALL_DIR)/iphonetexter

help:
	@printf "%s\n" \
		"make start      - bootstrap (build CLI, venv, deps) then open the control panel" \
		"                  (./start.sh start to skip the menu and launch the web UI)" \
		"make install    - install the 'iphonetexter' command to $(INSTALL_DIR)" \
		"                  (override with: make install INSTALL_DIR=/usr/local/bin)" \
		"make uninstall  - remove the 'iphonetexter' command" \
		"make dock-app   - build iPhoneTexter.app for the Dock (click = launch web UI)" \
		"make format     - swift format in-place" \
		"make lint       - swift format lint + swiftlint" \
		"make test       - sync version, patch deps, run swift test" \
		"make build      - universal release build into bin/" \
		"make build-dylib - build injectable dylib for Messages.app" \
		"make imsg       - clean rebuild + run debug binary (ARGS=...)" \
		"make clean      - swift package clean"

start:
	./start.sh $(ARGS)

install:
	@mkdir -p "$(INSTALL_DIR)"
	@repo_root="$$(pwd)"; \
	printf '#!/usr/bin/env bash\n# Generated by make install. Run `make install` again if you move the repo.\nSTART_SH="%s/start.sh"\nif [ ! -x "$$START_SH" ]; then\n  printf "iphonetexter: %%s not found.\\nThe repo may have moved or been deleted.\\nFrom the current repo location, run: make install\\n" "$$START_SH" >&2\n  exit 1\nfi\nexec "$$START_SH" "$$@"\n' "$$repo_root" > "$(WRAPPER)"
	@chmod +x "$(WRAPPER)"
	@printf "Installed:  %s\n" "$(WRAPPER)"
	@printf "Points to:  %s/start.sh\n" "$$(pwd)"
	@case ":$$PATH:" in \
		*":$(INSTALL_DIR):"*) printf "PATH:       OK\nRun it:     iphonetexter\n" ;; \
		*) printf "\nNote: %s is not on your PATH.\nAdd to ~/.zshrc (or ~/.bashrc):\n  export PATH=\"%s:\$$PATH\"\nThen 'exec zsh' to reload, or open a new terminal.\n" "$(INSTALL_DIR)" "$(INSTALL_DIR)" ;; \
	esac

uninstall:
	@if [ -e "$(WRAPPER)" ]; then \
		rm -f "$(WRAPPER)"; \
		printf "Removed: %s\n" "$(WRAPPER)"; \
	else \
		printf "Not installed: %s\n" "$(WRAPPER)"; \
	fi

dock-app:
	@scripts/install-dock-app.sh

format:
	swift format --in-place --recursive Sources Tests

lint:
	swift format lint --recursive Sources Tests
	swiftlint

test:
	scripts/generate-version.sh
	swift package resolve
	scripts/patch-deps.sh
	swift test

build:
	scripts/generate-version.sh
	swift package resolve
	scripts/patch-deps.sh
	scripts/build-universal.sh

# Build injectable dylib for Messages.app (DYLD_INSERT_LIBRARIES).
# Uses arm64e architecture to match Messages.app on Apple Silicon.
# Requires SIP disabled on the target machine to inject into system apps.
build-dylib:
	@echo "Building imsg-bridge-helper.dylib (injectable)..."
	@mkdir -p .build/release
	@clang -dynamiclib -arch arm64e -fobjc-arc \
		-Wno-arc-performSelector-leaks \
		-framework Foundation \
		-o .build/release/imsg-bridge-helper.dylib \
		Sources/IMsgHelper/IMsgInjected.m
	@echo "Built .build/release/imsg-bridge-helper.dylib"

imsg:
	scripts/generate-version.sh
	swift package resolve
	scripts/patch-deps.sh
	swift package clean
	swift build -c debug --product imsg
	./.build/debug/imsg $(ARGS)

clean:
	swift package clean
	@rm -f .build/release/imsg-bridge-helper.dylib
